/**
 * Shared currency options to prevent duplicates across the application
 * This file centralizes all currency definitions to avoid Mantine duplicate options errors
 */

/**
 * Function to get currency symbol for display
 */
export const getCurrencySymbol = (currency) => {
  const symbols = {
    USD: "$", CAD: "C$", MXN: "$", GTQ: "Q", HNL: "L", NIO: "C$", CRC: "₡", PAB: "B/.",
    EUR: "€", GBP: "£", CHF: "CHF", NOK: "kr", SEK: "kr", DKK: "kr", PLN: "zł", CZK: "Kč", HUF: "Ft", RON: "lei", BGN: "лв", HRK: "kn", RSD: "дин", BAM: "KM", MKD: "ден", ALL: "L", ISK: "kr", RUB: "₽", UAH: "₴", BYN: "Br", MDL: "L", GEL: "₾", AMD: "֏", AZN: "₼",
    JPY: "¥", CNY: "¥", KRW: "₩", INR: "₹", AUD: "A$", NZD: "NZ$", SGD: "S$", HKD: "HK$", TWD: "NT$", MYR: "RM", THB: "฿", IDR: "Rp", PHP: "₱", VND: "₫", LAK: "₭", KHR: "៛", MMK: "K", BND: "B$", PKR: "₨", LKR: "Rs", BDT: "৳", NPR: "₨", BTN: "Nu.", MVR: "Rf", AFN: "؋", UZS: "лв", KZT: "₸", KGS: "лв", TJS: "SM", TMT: "T", MNT: "₮",
    AED: "د.إ", SAR: "﷼", QAR: "ر.ق", KWD: "د.ك", BHD: ".د.ب", OMR: "ر.ع.", JOD: "د.ا", LBP: "ل.ل", SYP: "£", IQD: "ع.د", IRR: "﷼", TRY: "₺", ILS: "₪", EGP: "£", ZAR: "R", NGN: "₦", KES: "KSh", UGX: "USh", TZS: "TSh", ETB: "Br", GHS: "₵", XOF: "CFA", XAF: "FCFA", MAD: "د.م.", TND: "د.ت", DZD: "د.ج", LYD: "ل.د", SDG: "ج.س.", SOS: "S", DJF: "Fdj", ERN: "Nfk", RWF: "FRw", BIF: "FBu", MWK: "MK", ZMW: "ZK", BWP: "P", NAD: "N$", SZL: "L", LSL: "L", MZN: "MT", AOA: "Kz", CVE: "$", GMD: "D", GNF: "FG", LRD: "L$", SLE: "Le", STN: "Db", CDF: "FC", XPF: "₣", KMF: "CF", MGA: "Ar", MUR: "₨", SCR: "₨",
    BRL: "R$", ARS: "$", CLP: "$", COP: "$", PEN: "S/", UYU: "$U", PYG: "₲", BOB: "$b", VES: "Bs", GYD: "G$", SRD: "$",
    JMD: "J$", TTD: "TT$", BBD: "Bds$", BSD: "B$", BZD: "BZ$", XCD: "EC$", AWG: "ƒ", ANG: "ƒ", CUP: "₱", DOP: "RD$", HTG: "G", KYD: "CI$", BMD: "BD$", FJD: "FJ$", TOP: "T$", WST: "WS$", VUV: "VT", SBD: "SI$", PGK: "K", TVD: "TV$", NRU: "A$", KID: "A$"
  };
  return symbols[currency] || currency;
};

export const currencyOptions = [
  // North America
  { value: "USD", label: "USD - US Dollar" },
  { value: "CAD", label: "CAD - Canadian Dollar" },
  { value: "MXN", label: "MXN - Mexican Peso" },
  { value: "GTQ", label: "GTQ - Guatemalan Quetzal" },
  { value: "HNL", label: "HNL - Honduran Lempira" },
  { value: "NIO", label: "NIO - Nicaraguan Córdoba" },
  { value: "CRC", label: "CRC - Costa Rican Colón" },
  { value: "PAB", label: "PAB - Panamanian Balboa" },
  
  // Europe
  { value: "EUR", label: "EUR - Euro" },
  { value: "GBP", label: "GBP - British Pound" },
  { value: "CHF", label: "CHF - Swiss Franc" },
  { value: "NOK", label: "NOK - Norwegian Krone" },
  { value: "SEK", label: "SEK - Swedish Krona" },
  { value: "DKK", label: "DKK - Danish Krone" },
  { value: "PLN", label: "PLN - Polish Złoty" },
  { value: "CZK", label: "CZK - Czech Koruna" },
  { value: "HUF", label: "HUF - Hungarian Forint" },
  { value: "RON", label: "RON - Romanian Leu" },
  { value: "BGN", label: "BGN - Bulgarian Lev" },
  { value: "HRK", label: "HRK - Croatian Kuna" },
  { value: "RSD", label: "RSD - Serbian Dinar" },
  { value: "BAM", label: "BAM - Bosnia-Herzegovina Convertible Mark" },
  { value: "MKD", label: "MKD - Macedonian Denar" },
  { value: "ALL", label: "ALL - Albanian Lek" },
  { value: "ISK", label: "ISK - Icelandic Króna" },
  { value: "RUB", label: "RUB - Russian Ruble" },
  { value: "UAH", label: "UAH - Ukrainian Hryvnia" },
  { value: "BYN", label: "BYN - Belarusian Ruble" },
  { value: "MDL", label: "MDL - Moldovan Leu" },
  { value: "GEL", label: "GEL - Georgian Lari" },
  { value: "AMD", label: "AMD - Armenian Dram" },
  { value: "AZN", label: "AZN - Azerbaijani Manat" },
  
  // Asia-Pacific
  { value: "JPY", label: "JPY - Japanese Yen" },
  { value: "CNY", label: "CNY - Chinese Yuan" },
  { value: "KRW", label: "KRW - South Korean Won" },
  { value: "INR", label: "INR - Indian Rupee" },
  { value: "AUD", label: "AUD - Australian Dollar" },
  { value: "NZD", label: "NZD - New Zealand Dollar" },
  { value: "SGD", label: "SGD - Singapore Dollar" },
  { value: "HKD", label: "HKD - Hong Kong Dollar" },
  { value: "TWD", label: "TWD - Taiwan Dollar" },
  { value: "MYR", label: "MYR - Malaysian Ringgit" },
  { value: "THB", label: "THB - Thai Baht" },
  { value: "IDR", label: "IDR - Indonesian Rupiah" },
  { value: "PHP", label: "PHP - Philippine Peso" },
  { value: "VND", label: "VND - Vietnamese Dong" },
  { value: "LAK", label: "LAK - Lao Kip" },
  { value: "KHR", label: "KHR - Cambodian Riel" },
  { value: "MMK", label: "MMK - Myanmar Kyat" },
  { value: "BND", label: "BND - Brunei Dollar" },
  { value: "PKR", label: "PKR - Pakistani Rupee" },
  { value: "LKR", label: "LKR - Sri Lankan Rupee" },
  { value: "BDT", label: "BDT - Bangladeshi Taka" },
  { value: "NPR", label: "NPR - Nepalese Rupee" },
  { value: "BTN", label: "BTN - Bhutanese Ngultrum" },
  { value: "MVR", label: "MVR - Maldivian Rufiyaa" },
  { value: "AFN", label: "AFN - Afghan Afghani" },
  { value: "UZS", label: "UZS - Uzbekistani Som" },
  { value: "KZT", label: "KZT - Kazakhstani Tenge" },
  { value: "KGS", label: "KGS - Kyrgyzstani Som" },
  { value: "TJS", label: "TJS - Tajikistani Somoni" },
  { value: "TMT", label: "TMT - Turkmenistani Manat" },
  { value: "MNT", label: "MNT - Mongolian Tugrik" },
  
  // Middle East & Africa
  { value: "AED", label: "AED - UAE Dirham" },
  { value: "SAR", label: "SAR - Saudi Riyal" },
  { value: "QAR", label: "QAR - Qatari Riyal" },
  { value: "KWD", label: "KWD - Kuwaiti Dinar" },
  { value: "BHD", label: "BHD - Bahraini Dinar" },
  { value: "OMR", label: "OMR - Omani Rial" },
  { value: "JOD", label: "JOD - Jordanian Dinar" },
  { value: "LBP", label: "LBP - Lebanese Pound" },
  { value: "SYP", label: "SYP - Syrian Pound" },
  { value: "IQD", label: "IQD - Iraqi Dinar" },
  { value: "IRR", label: "IRR - Iranian Rial" },
  { value: "TRY", label: "TRY - Turkish Lira" },
  { value: "ILS", label: "ILS - Israeli Shekel" },
  { value: "EGP", label: "EGP - Egyptian Pound" },
  { value: "ZAR", label: "ZAR - South African Rand" },
  { value: "NGN", label: "NGN - Nigerian Naira" },
  { value: "KES", label: "KES - Kenyan Shilling" },
  { value: "UGX", label: "UGX - Ugandan Shilling" },
  { value: "TZS", label: "TZS - Tanzanian Shilling" },
  { value: "ETB", label: "ETB - Ethiopian Birr" },
  { value: "GHS", label: "GHS - Ghanaian Cedi" },
  { value: "XOF", label: "XOF - West African CFA Franc" },
  { value: "XAF", label: "XAF - Central African CFA Franc" },
  { value: "MAD", label: "MAD - Moroccan Dirham" },
  { value: "TND", label: "TND - Tunisian Dinar" },
  { value: "DZD", label: "DZD - Algerian Dinar" },
  { value: "LYD", label: "LYD - Libyan Dinar" },
  { value: "SDG", label: "SDG - Sudanese Pound" },
  { value: "SOS", label: "SOS - Somali Shilling" },
  { value: "DJF", label: "DJF - Djiboutian Franc" },
  { value: "ERN", label: "ERN - Eritrean Nakfa" },
  { value: "RWF", label: "RWF - Rwandan Franc" },
  { value: "BIF", label: "BIF - Burundian Franc" },
  { value: "MWK", label: "MWK - Malawian Kwacha" },
  { value: "ZMW", label: "ZMW - Zambian Kwacha" },
  { value: "BWP", label: "BWP - Botswana Pula" },
  { value: "NAD", label: "NAD - Namibian Dollar" },
  { value: "SZL", label: "SZL - Swazi Lilangeni" },
  { value: "LSL", label: "LSL - Lesotho Loti" },
  { value: "MZN", label: "MZN - Mozambican Metical" },
  { value: "AOA", label: "AOA - Angolan Kwanza" },
  { value: "CVE", label: "CVE - Cape Verdean Escudo" },
  { value: "GMD", label: "GMD - Gambian Dalasi" },
  { value: "GNF", label: "GNF - Guinean Franc" },
  { value: "LRD", label: "LRD - Liberian Dollar" },
  { value: "SLE", label: "SLE - Sierra Leonean Leone" },
  { value: "STN", label: "STN - São Tomé and Príncipe Dobra" },
  { value: "CDF", label: "CDF - Congolese Franc" },
  { value: "XPF", label: "XPF - CFP Franc" },
  { value: "KMF", label: "KMF - Comorian Franc" },
  { value: "MGA", label: "MGA - Malagasy Ariary" },
  { value: "MUR", label: "MUR - Mauritian Rupee" },
  { value: "SCR", label: "SCR - Seychellois Rupee" },
  
  // South America
  { value: "BRL", label: "BRL - Brazilian Real" },
  { value: "ARS", label: "ARS - Argentine Peso" },
  { value: "CLP", label: "CLP - Chilean Peso" },
  { value: "COP", label: "COP - Colombian Peso" },
  { value: "PEN", label: "PEN - Peruvian Sol" },
  { value: "UYU", label: "UYU - Uruguayan Peso" },
  { value: "PYG", label: "PYG - Paraguayan Guaraní" },
  { value: "BOB", label: "BOB - Bolivian Boliviano" },
  { value: "VES", label: "VES - Venezuelan Bolívar" },
  { value: "GYD", label: "GYD - Guyanese Dollar" },
  { value: "SRD", label: "SRD - Surinamese Dollar" },
  
  // Caribbean & Pacific
  { value: "JMD", label: "JMD - Jamaican Dollar" },
  { value: "TTD", label: "TTD - Trinidad and Tobago Dollar" },
  { value: "BBD", label: "BBD - Barbadian Dollar" },
  { value: "BSD", label: "BSD - Bahamian Dollar" },
  { value: "BZD", label: "BZD - Belize Dollar" },
  { value: "XCD", label: "XCD - East Caribbean Dollar" },
  { value: "AWG", label: "AWG - Aruban Florin" },
  { value: "ANG", label: "ANG - Netherlands Antillean Guilder" },
  { value: "CUP", label: "CUP - Cuban Peso" },
  { value: "DOP", label: "DOP - Dominican Peso" },
  { value: "HTG", label: "HTG - Haitian Gourde" },
  { value: "KYD", label: "KYD - Cayman Islands Dollar" },
  { value: "BMD", label: "BMD - Bermudian Dollar" },
  { value: "FJD", label: "FJD - Fijian Dollar" },
  { value: "TOP", label: "TOP - Tongan Paʻanga" },
  { value: "WST", label: "WST - Samoan Tala" },
  { value: "VUV", label: "VUV - Vanuatu Vatu" },
  { value: "SBD", label: "SBD - Solomon Islands Dollar" },
  { value: "PGK", label: "PGK - Papua New Guinean Kina" },
  { value: "TVD", label: "TVD - Tuvaluan Dollar" },
  { value: "NRU", label: "NRU - Nauruan Dollar" },
  { value: "KID", label: "KID - Kiribati Dollar" }
];

export default currencyOptions;